### ISSUE TITLE
Developer may forget to generate chains

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/chains#11]
@andreogle 
`src/generated/` is not gitignore'd. This means that the developer needs to manually run `chains:generate` (or `build`) after updating `chains/`. Two options:
- gitignore `src/generated/` (my choice)
- Add `build` to a git hook

**Comment by andreogle** [comment]
A third option is to `deepEqual` check each JSON file's content matches the respective content in `CHAINS`. I wanted to add this to `validate:chains` but then forgot. Checking the only the number of chains matches isn't enough. It's very easy to add and no reason not to do this imo.

I couldn't decide if I wanted `src/generated` checked in or not. I don't really mind either way

**Comment by bbenligiray** [comment]
That also works for me
