### ISSUE TITLE
Update monitoring to fetch RPC providers information from the @api3dao/chains repository

### ISSUE THREAD

**Issue by BTT21000** [api3dao/chains#122]
As discussed on 06/11/23 [chain integrations call](https://drive.google.com/file/d/1SEWv7dmlvZxJcJ5QX-n4HLZ9w4UhckqB/view), we should update our `monitor.reblok.io` monitoring so that it fetches the RPC providers information from the [@api3dao/chains](https://github.com/api3dao/chains) repository.

Blocked by https://github.com/api3dao/tasks/issues/182

**Comment by bdrhn9** [comment]
Monitoring utilities were updated to utilize `api3dao/chains` repository. Also ownership was transferred from `nodaryio` to `api3dao` organization. Following issues are solved regards to this epic issue:

- https://github.com/api3dao/nodary-rpc-watcher/issues/10
- https://github.com/api3dao/nodary-rpc-watcher/issues/11
- https://github.com/api3dao/nodary-rpc-watcher/issues/12
- https://github.com/api3dao/nodary-rpc-watcher/issues/13
- https://github.com/api3dao/nodary-rpc-watcher/issues/16
- https://github.com/api3dao/nodary-rpc-watcher/issues/18
- https://github.com/api3dao/nodary-rpc-watcher/issues/20
- https://github.com/api3dao/nodary-rpc-watcher/issues/22
- https://github.com/api3dao/nodary-rpc-watcher/issues/23
- https://github.com/api3dao/nodary-rpc-watcher/issues/24
