### ISSUE TITLE
Finalize repo QA compliance

### ISSUE THREAD

**Issue by BTT21000** [api3dao/chains#196]
As part of the TM issue https://github.com/api3dao/tasks/issues/849 for QA, some requirements need to be addressed:

### Package setup requirements as per [new_package_creation_checklist.md](https://github.com/api3dao/tasks/blob/main/Technical%20management/Tasks%20documentation/new_package_creation_checklist.md):
- [x] Add relevant package.json fields as applicable (e.g. such that repo links and keywords show up in NPM, compare [this](https://www.npmjs.com/package/@material/button) to [this](https://www.npmjs.com/package/@api3/ois))
- [x] Verify the setup of security vulnerability scanning tools (e.g. Renovate) for the codebase and dependencies.

**Comment by andreogle** [comment]
Relevant `package.json` fields added here: https://github.com/api3dao/chains/pull/197
Also checked that security vulnerability scanning is enabled
