### ISSUE TITLE
Remove blockTimeMs (?)

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/chains#236]
- We used to use this in Market 2.0 to decide on the block confirmations but that no longer applies
- It's a hassle in new chain integrations
- We don't update them regularly
- The current implementation doesn't work for most of the new chains we integrate (because they haven't seen [400,000](https://github.com/api3dao/chains/blob/main/scripts/calculate-average-block-times.ts#L6) blocks yet)
- The result is often [2000 ms](https://github.com/api3dao/chains/blob/main/chains/sx-testnet.json#L3) for some reason, though when I check it looks like it worked correctly (in that 400,000 block ago was actually exactly 400,000 * 2000 ms ago) but I didn't investigate deeper

**Comment by dcroote** [comment]
> We don't update them regularly

We do, via a scheduled monthly GitHub Action e.g. #208, but that is a bit beside the point if they're no longer used by anything

**Comment by andreogle** [comment]
No objections from me for removing `blockTimeMs`. It did feel a bit hacky for my liking
