### ISSUE TITLE
Add `supports` flags to chains

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/chains#3]
Currently, the common property of all chains in @api3/chains is that Api3ServerV1 is deployed on them. However, [we now need to add chains that Api3ServerV1 is not necessarily deployed on](https://github.com/api3dao/chains/issues/2), [which will create confusion about which chains are supported for what](https://github.com/api3dao/data-feed-reader-example#supported-networks). On top of that, ChainAPI supports an entirely independent subset of all these chains.

I propose that we add a `supports` field to the chain object as in
```json
{
  "supports": [ "AirnodeRrpV0", "Api3ServerV1", "ChainAPI" ],
  ...
}
```

@andreogle wdyt?

**Comment by andreogle** [comment]
Yeah sounds good to me. I can't think of a better structure for this at the moment.

I'm hoping to get [the TypeScript PR](https://github.com/api3dao/chains/pull/1) merged either today or tomorrow, but feel free to add this to current `main` if it's urgent and I'll merge those changes into that PR

**Comment by bbenligiray** [comment]
As a note, I'm currently doing this partially here https://github.com/api3dao/airnode-protocol-v1/blob/main/src/supported-chains.js

**Comment by andreogle** [comment]
Closing this issue. See related (closed) PR for more info: https://github.com/api3dao/chains/pull/86
