### ISSUE TITLE
Update `zircuit` default rpc provider

### ISSUE THREAD

**Issue by hiletmis** [api3dao/chains#393]
Zircuit chain had been utilizing private rpc. A new public rpc has been announced.

* Replace proxied rpc url with public rpc.

See: https://docs.zircuit.com/dev-tools/rpc-endpoints

**Comment by BTT21000** [comment]
It appears that the zurcuit RPCs are now officially public as documented there:
https://docs.zircuit.com/dev-tools/rpc-endpoints

> The RPC Endpoints for Zircuit are:
> 
> https://zircuit1-mainnet.p2pify.com/
> Chainstack (chainstack.com)
> 
> https://zircuit-mainnet.drpc.org 
> DRPC (drpc.org)
> 
> https://zircuit1-mainnet.liquify.com
> Liquify (liquify.com)
> 
> The Chain Id is 48900. 

This issue can be updated and finalised accordingly.
