### ISSUE TITLE
Sonic testnet explorer URL does not work

### ISSUE THREAD

**Issue by wkande** [api3dao/chains#436]
The explorer URL does not work: `https://public-sonic.fantom.network/`.

```
  {
    "alias": "sonic-testnet",
     ...
    "explorer": {
      "browserUrl": "https://public-sonic.fantom.network/"
    },
    ...
    "testnet": true
  },

```

**Comment by dcroote** [comment]
For me that URL redirects to https://testnet.soniclabs.com/ which is also what the [docs describe](https://docs.soniclabs.com/sonic/testnet/getting-started).
