### ISSUE TITLE
Default taiko provider gives a CORS error

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/chains#487]
When I tried to execute txes on the manager multisig, I received a CORS error from https://github.com/api3dao/chains/blob/main/chains/taiko.json#L18 (because I was calling it from my browser) and had to switch my RPC URL. I assume this also affects the market.
Maybe we should check if a provider can be used with a browser before setting it as the default one. This is not a common issue though, so we can also wait and see if it happens again. Meanwhile, the default taiko provider should be changed.
@bdrhn9 for visibility

**Comment by bdrhn9** [comment]
Default provider has been changed in https://github.com/api3dao/chains/pull/489. I'm closing this issue as completed. 

> Maybe we should check if a provider can be used with a browser before setting it as the default one.

Created https://github.com/api3dao/chains/issues/494 to track this.
