### ISSUE TITLE
Allow Hardhat RPC URL to be specified in environment variables similar to the Etherscan API key

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/chains#51]
It's a bit annoying to be strictly limited to the RPC URL that this package provides while, for example, deploying a contract. It would be handy if the Hardhat config generation referred to the environment variables for an RPC URL similar to the Etherscan API key.

**Comment by andreogle** [comment]
Just to clarify, you mean adding new (optional) ENV variables like:

```sh
# 1. "HTTP_" to leave the option of adding WSS URLs later
# 2. Chain alias as a suffix to make them easier to find/sort (like with the Etherscan ones)
HTTP_RPC_URL_ARBITRUM_GOERLI_TESTNET
HTTP_RPC_URL_ARBITRUM_NOVA
HTTP_RPC_URL_ETHEREUM
```

Then update this line
https://github.com/api3dao/chains/blob/db59bd3b39ac351f204960631b6b5440006008b7/src/hardhat-config.ts#L65

To something like:

```ts
url: process.env[getNetworkRPCEnvName(chain)] || chain.providerUrl
```

**Comment by bbenligiray** [comment]
Exactly, though I would prefer `HARDHAT_HTTP_RPC_URL_ARBITRUM`

**Comment by bbenligiray** [comment]
Also it may be a good idea for these to be pre-populated by the default values in `example.env` generation in case people think they are not optional (or you suspect that a provider isn't working you'd want to check the URL and currently it's not very easy for an @api3/chains user to do that, you either needs to print `chains` or go to the repo)
