### ISSUE TITLE
Ping providers (at least) as a part of CI

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/chains#70]
We have [a lightweight script that pings providers](https://github.com/api3dao/chains/blob/main/package.json#L26). If that runs as a part of the CI, it would provide a lot of protection against issues such as the one fixed here https://github.com/api3dao/chains/pull/69

**Comment by andreogle** [comment]
Do you have anything in mind for how you would like this to work? Typically we wouldn't want a faulty provider to hold up our CI, so I guess this would probably be a parallel CI process. i.e. separated from the process that runs linting, unit tests and builds the app.

Maybe something like:

- An Github workflow that runs on an hourly cron schedule
- It just runs the ping providers script
- Any failing providers are posted to Slack (?)
- Maybe there's a badge on the README as well that shows x/49 chains responsive. Not sure how difficult this is to implement though

**Comment by dcroote** [comment]
Bullets 1-3 sound good to me, though I think we'd be fine with daily (or less?) rather than hourly.

**Comment by bbenligiray** [comment]
A daily test sounds good, but it wouldn't stop us from merging and releasing with an invalid provider URL.

**Comment by andreogle** [comment]
We do currently validate `providerUrl` values are a valid URL here: https://github.com/api3dao/chains/blob/4f71dbbcee661bcc2d169ff9eda4355c0965fe71/src/types.ts#L25

I don't like the idea of pinging each providerUrl blocking us from merging & releasing though. We have 49 chains at the moment and this list is only going to grow larger. There's a decent chance that one of them is being flakey/having some downtime which will make the process of merging & releasing way more painful.

**Comment by bbenligiray** [comment]
It wasn't a valid provider URL in that it was a block explorer URL
